version: '3.8'
services:
  app:
    build:
      context: .
    container_name: src
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - mongodb
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "${DB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
